name: 'Setup CUDA'
description: 'Install and configure CUDA toolkit for GPU CI'

inputs:
  cuda-version:
    description: 'CUDA version to install'
    required: false
    default: '12.4'

runs:
  using: 'composite'
  steps:
    - name: Check for existing CUDA installation
      id: cuda-check
      shell: bash
      run: |
        if command -v nvcc &> /dev/null; then
          INSTALLED_VERSION=$(nvcc --version | grep "release" | awk '{print $5}' | cut -d',' -f1)
          echo "cuda_installed=true" >> $GITHUB_OUTPUT
          echo "cuda_version=$INSTALLED_VERSION" >> $GITHUB_OUTPUT
          echo "CUDA $INSTALLED_VERSION already installed"
        else
          echo "cuda_installed=false" >> $GITHUB_OUTPUT
          echo "CUDA not found, will install"
        fi

    - name: Install CUDA Toolkit (Ubuntu)
      if: steps.cuda-check.outputs.cuda_installed == 'false' && runner.os == 'Linux'
      shell: bash
      run: |
        # Add NVIDIA package repository
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update

        # Install CUDA toolkit
        CUDA_PKG="cuda-toolkit-$(echo ${{ inputs.cuda-version }} | tr '.' '-')"
        sudo apt-get install -y $CUDA_PKG

        # Cleanup
        rm -f cuda-keyring_1.1-1_all.deb

    - name: Configure CUDA environment
      shell: bash
      run: |
        # Find CUDA installation
        if [ -d "/usr/local/cuda-${{ inputs.cuda-version }}" ]; then
          CUDA_HOME="/usr/local/cuda-${{ inputs.cuda-version }}"
        elif [ -d "/usr/local/cuda" ]; then
          CUDA_HOME="/usr/local/cuda"
        else
          echo "Warning: CUDA installation not found in expected locations"
          CUDA_HOME="/usr/local/cuda"
        fi

        # Set environment variables
        echo "CUDA_HOME=$CUDA_HOME" >> $GITHUB_ENV
        echo "CUDA_PATH=$CUDA_HOME" >> $GITHUB_ENV
        echo "$CUDA_HOME/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV

        # For cudarc crate
        echo "CUDA_COMPUTE_CAP=80" >> $GITHUB_ENV  # Default to Ampere (A100/etc)

    - name: Verify CUDA installation
      shell: bash
      run: |
        echo "=== CUDA Configuration ==="
        echo "CUDA_HOME: $CUDA_HOME"
        which nvcc || echo "nvcc not in PATH"
        nvcc --version || echo "nvcc version check failed"

        echo ""
        echo "=== GPU Information ==="
        nvidia-smi || echo "nvidia-smi not available (expected on non-GPU runners)"

        echo ""
        echo "=== CUDA Libraries ==="
        ls -la $CUDA_HOME/lib64/*.so 2>/dev/null | head -10 || echo "No CUDA libraries found"

    - name: Cache CUDA compilation artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/cuda
          target/release/.fingerprint/*cuda*
          target/release/deps/*cuda*
        key: cuda-${{ inputs.cuda-version }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cuda-${{ inputs.cuda-version }}-${{ runner.os }}-
